print("XOR with 0 - keeps the bit the same.  Press Enter ")
print(" 5 ^ 0 = ", 5^0)
print(" 9 ^ 0 = ", 9^0)
print("XOR with itself - turns the bit OFF.  Press Enter ")
print(" 5 ^ 5 = ", 5^5)
print(" 9 ^ 9 = ", 9^9)
n = int(input("Enter a number (try 6 or 11): "))
guess = input("What is 5 ^ " + str(n) + " ^ 5? (try to guess the answer): ")
print("XOR cancels - the first 5 and the last 5.  Press Enter ")
print(" your guess:", guess, "  answer:", 5 ^ n ^ 5)